### ISSUE TITLE
Exception when i start server

### ISSUE THREAD

**Issue by 96hemanth** [pravams/nodejs-magento#1]
<Drive>\nodejs-magento>node index.js
listening on 3000
<Drive>\nodejs-magento\node_modules\soap\lib\wsdl.js:560
      this.parts[part.$name].namespace = nsName.namespace;
                                       ^
TypeError: Cannot assign to read only property 'namespace' of xsd:string
    at MessageElement.postProcess (<Drive>\nodejs-magento
\node_modules\soap\lib\wsdl.js:560:40)
    at OperationElement.postProcess (<Drive>\nodejs-magen
to\node_modules\soap\lib\wsdl.js:641:13)
    at PortTypeElement.postProcess (<Drive>\nodejs-magent
o\node_modules\soap\lib\wsdl.js:661:11)
    at BindingElement.postProcess (<Drive>\nodejs-magento
\node_modules\soap\lib\wsdl.js:675:14)
    at ServiceElement.postProcess (<Drive>\nodejs-magento
\node_modules\soap\lib\wsdl.js:710:15)
    at <Drive>\nodejs-magento\node_modules\soap\lib\wsdl.
js:1006:26
    at <Drive>\nodejs-magento\node_modules\soap\lib\wsdl.
js:1102:7
    at WSDL._processNextInclude (<Drive>\nodejs-magento\n
ode_modules\soap\lib\wsdl.js:1083:12)
    at null.callback (<Drive>\nodejs-magento\node_modules
\soap\lib\wsdl.js:1101:10)
    at <Drive>\nodejs-magento\node_modules\soap\lib\wsdl.
js:1041:12

**Comment by engrKaka** [comment]
Hi Pravams, nice thing bro, but i am also getting an error like hemanth.
it says
root@usol-OptiPlex-755:/var/www/html/nodejs-magento# node index.js
listening on 3000
/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:560
      this.parts[part.$name].namespace = nsName.namespace;
                                       ^

TypeError: Cannot create property 'namespace' on string 'xsd:string'
    at MessageElement.postProcess (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:560:40)
    at OperationElement.postProcess (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:641:13)
    at PortTypeElement.postProcess (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:661:11)
    at BindingElement.postProcess (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:675:14)
    at ServiceElement.postProcess (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:710:15)
    at /var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:1006:26
    at /var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:1102:7
    at WSDL._processNextInclude (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:1083:12)
    at .callback (/var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:1101:10)
    at /var/www/html/nodejs-magento/node_modules/soap/lib/wsdl.js:1041:12
root@usol-OptiPlex-755:/var/www/html/nodejs-magento#
